branches:
  only: master

notifications:
  email: false

env:
  global:
    - secure: AhAbbLGFddBQ6GmMnyV/AhDJuug2Rukdnl+7Q1cAsiRr+QVJGVqw9ChioX9kdiLHmsonCnf0kjXMP7GH6joi63swtnpSWdznJe9ZzHVsD4CAYQB+PZAsOvnnO/gudML8vlii01TzPYpwJMaiKaruBfTZ8EuSkHavaCnXT6I3evcaDzZxP5m0/5BHHPIcwL4P4SmIpUrt4CrqwMO4fIukbAFLBBW+cpYhsUxnuVY/GEIvjjKQFUCr24f8FU0u2q14kdfNEWUB0Dx/QbZ02Dz0s1km2Z+xX8vWFIzUE9ljltpSNGorwlLvzL0YmceF0M8cjeW9B9NCJxtFt5ezknv+ZrQGFjrCBqwU6mapG8T7rQFQpLqpSvCNOwm/XR/rjNgZ7VRJ3Y8LTXfsZq/3IDK7evhhX+JsTDn9TSVdUKLmk5YVaPzoFuVApwfk5RiOsnWHym+cOL1gIYrpeM2kMv66//JzZ8KU4pYsrzQdlnleKNQcUQPAisykh0eQfTlANXgBpyAkOzc4Kn005VFwRYi4f+KSnQkdHlRQbvNaB77lVwb3aVjmEqKoAb/VaExcdBkHvZoc8kGSNUYnEzn8ehwGn1oywWCQHu8T8hv5QjrqUi44yVrXcf7lC0B9Kx50LO12+Tx23F1oXiFbqPYGBRHhdB/IjLEAjq1f2M7Z8GBBrcg=
    - secure: Tq61wRBX5lnwWVFs8iaqdeyVS5l6SfxbruFx+Vy91m2x5wyycT2fdTsECCn69pPNq/khJ0PMTmf9PWwVNOccOsLaZ9sKWm9/w2idf4krZThHvuxMA/F4qoCIP29cQStWGPrMjkAxovgbszijiLjA02QeDjX7deALt6OlIvLJYxW+UZIwUJI4aiuLpNFF7Wh9kG1V7KqL2WYMBIUk6NoUP9kN9MabP7aTxswjlB/JMEeJCBqaNOKc82sGobTvrd1cUVRHO3WmgCFbxCvO/BmiNw0bvMqA5fZ58qH1J8MoKkkE8X16DYgoa5XuhBx5VSfMOc7tDMW3gMzp+BCoRzKGbfqCHMXhludSr8Y0ywytg5a7QGEs8gPDIrzlwIWyzQhAupX6gOawqghQeYReic4iIA3fDoUHl+gRmXg2oAJLsSJJ1kwJ6FWX49roTGpahFOo5KBlEf2Gfh2UPIqUN8nkh/lSI7aJae1peNLicBAAMjAezVHR0CL7yN33jvk3LLUwSp773IoeGmzi/fo8qLFwDwxvuAlzfWIfCy54olYNp59wTfbso8zNlHweDEYAX8Tg6BSNBjigaFcnGDgJabTvKXRFzxJKhEG3eHcoq/2vteKjEuM4qHFgdCPZA5xc/r4T33E7DTIHooc2N0PltNN6uksrUBOrjnhSjaZHaClI+nU=

language: python

python: 3.6

install:
  - pip install codecov
  - pip install .

script: python setup.py test

after_success: codecov
