branches:
  only: master

notifications:
  email: false

env:
  global:
    - secure: AhAbbLGFddBQ6GmMnyV/AhDJuug2Rukdnl+7Q1cAsiRr+QVJGVqw9ChioX9kdiLHmsonCnf0kjXMP7GH6joi63swtnpSWdznJe9ZzHVsD4CAYQB+PZAsOvnnO/gudML8vlii01TzPYpwJMaiKaruBfTZ8EuSkHavaCnXT6I3evcaDzZxP5m0/5BHHPIcwL4P4SmIpUrt4CrqwMO4fIukbAFLBBW+cpYhsUxnuVY/GEIvjjKQFUCr24f8FU0u2q14kdfNEWUB0Dx/QbZ02Dz0s1km2Z+xX8vWFIzUE9ljltpSNGorwlLvzL0YmceF0M8cjeW9B9NCJxtFt5ezknv+ZrQGFjrCBqwU6mapG8T7rQFQpLqpSvCNOwm/XR/rjNgZ7VRJ3Y8LTXfsZq/3IDK7evhhX+JsTDn9TSVdUKLmk5YVaPzoFuVApwfk5RiOsnWHym+cOL1gIYrpeM2kMv66//JzZ8KU4pYsrzQdlnleKNQcUQPAisykh0eQfTlANXgBpyAkOzc4Kn005VFwRYi4f+KSnQkdHlRQbvNaB77lVwb3aVjmEqKoAb/VaExcdBkHvZoc8kGSNUYnEzn8ehwGn1oywWCQHu8T8hv5QjrqUi44yVrXcf7lC0B9Kx50LO12+Tx23F1oXiFbqPYGBRHhdB/IjLEAjq1f2M7Z8GBBrcg=

language: python

python: 3.6

install: pip install .

script: python setup.py test
